=== ilist2/linac-lego/LinacLego/test/dtdFiles/FieldProfile.dtd
<!ELEMENT fieldProfile (d+)>
<!ATTLIST fieldProfile
 	title        CDATA      #REQUIRED
 	storedEnergy CDATA      #REQUIRED
 	length       CDATA      #REQUIRED
	storedEnergyUnit CDATA  #REQUIRED
 	lengthUnit   CDATA      #REQUIRED
 	fieldUnit    CDATA      #REQUIRED >
<!ELEMENT d (#PCDATA) >
<!ATTLIST d
	id CDATA #REQUIRED>

=== ilist2/linac-lego/LinacLego/test/xmlFiles/spokeFieldMap.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE fieldProfile SYSTEM "../dtdFiles/FieldProfile.dtd">
<fieldProfile title="Spoke_F2F" storedEnergy="1.0" length="994.0" lengthUnit="mm" storedEnergyUnit="Joules" fieldUnit="Volt/m">
	<d id="0">0.0</d>
	<d id="1">0.0</d>
	<d id="2">0.0</d>
	<d id="3">0.0</d>
	<d id="4">0.0</d>
	<d id="5">0.0</d>
	<d id="6">0.0</d>
	<d id="7">0.0</d>
	<d id="8">0.0</d>
	<d id="9">0.0</d>
	<d id="10">0.0</d>
	<d id="11">0.0</d>
	<d id="12">0.0</d>
	<d id="13">0.0</d>
	<d id="14">0.0</d>
	<d id="15">0.0</d>
	<d id="16">0.0</d>
	<d id="17">0.0</d>
	<d id="18">0.0</d>
	<d id="19">0.0</d>
	<d id="20">0.0</d>
	<d id="21">0.0</d>
	<d id="22">0.0</d>
	<d id="23">0.0</d>
	<d id="24">0.0</d>
	<d id="25">0.0</d>
	<d id="26">0.0</d>
	<d id="27">0.0</d>
	<d id="28">0.0</d>
	<d id="29">0.0</d>
	<d id="30">0.0</d>
	<d id="31">0.0</d>
	<d id="32">0.0</d>
	<d id="33">0.0</d>
	<d id="34">0.0</d>
	<d id="35">0.0</d>
	<d id="36">0.0</d>
	<d id="37">0.0</d>
	<d id="38">0.0</d>
	<d id="39">0.0</d>
	<d id="40">0.0</d>
	<d id="41">0.0</d>
	<d id="42">0.0</d>
	<d id="43">0.0</d>
	<d id="44">0.0</d>
	<d id="45">0.0</d>
	<d id="46">0.0</d>
	<d id="47">0.0</d>
	<d id="48">0.0</d>
	<d id="49">0.0</d>
	<d id="50">0.0</d>
	<d id="51">0.0</d>
	<d id="52">0.0</d>
	<d id="53">0.0</d>
	<d id="54">0.0</d>
	<d id="55">0.0</d>
	<d id="56">0.0</d>
	<d id="57">1.0E-6</d>
	<d id="58">1.0E-6</d>
	<d id="59">1.0E-6</d>
	<d id="60">1.0E-6</d>
	<d id="61">1.0E-6</d>
	<d id="62">1.0E-6</d>
	<d id="63">1.0E-6</d>
	<d id="64">1.0E-6</d>
	<d id="65">1.0E-6</d>
	<d id="66">1.0E-6</d>
	<d id="67">1.0E-6</d>
	<d id="68">1.0E-6</d>
	<d id="69">1.0E-6</d>
	<d id="70">1.0E-6</d>
	<d id="71">1.0E-6</d>
	<d id="72">1.0E-6</d>
	<d id="73">1.0E-6</d>
	<d id="74">1.0E-6</d>
	<d id="75">1.0E-6</d>
	<d id="76">1.0E-6</d>
	<d id="77">1.0E-6</d>
	<d id="78">1.0E-6</d>
	<d id="79">1.0E-6</d>
	<d id="80">1.0E-6</d>
	<d id="81">1.0E-6</d>
	<d id="82">1.0E-6</d>
	<d id="83">1.0E-6</d>
	<d id="84">1.0E-6</d>
	<d id="85">1.0E-6</d>
	<d id="86">1.0E-6</d>
	<d id="87">1.0E-6</d>
	<d id="88">2.0E-6</d>
	<d id="89">2.0E-6</d>
	<d id="90">2.0E-6</d>
	<d id="91">2.0E-6</d>
	<d id="92">2.0E-6</d>
	<d id="93">2.0E-6</d>
	<d id="94">2.0E-6</d>
	<d id="95">2.0E-6</d>
	<d id="96">2.0E-6</d>
	<d id="97">2.0E-6</d>
	<d id="98">2.0E-6</d>
	<d id="99">2.0E-6</d>
	<d id="100">2.0E-6</d>
	<d id="101">2.0E-6</d>
	<d id="102">2.0E-6</d>
	<d id="103">3.0E-6</d>
	<d id="104">3.0E-6</d>
	<d id="105">3.0E-6</d>
	<d id="106">3.0E-6</d>
	<d id="107">3.0E-6</d>
	<d id="108">3.0E-6</d>
	<d id="109">3.0E-6</d>
	<d id="110">3.0E-6</d>
	<d id="111">3.0E-6</d>
	<d id="112">4.0E-6</d>
	<d id="113">4.0E-6</d>
	<d id="114">4.0E-6</d>
	<d id="115">4.0E-6</d>
	<d id="116">4.0E-6</d>
	<d id="117">4.0E-6</d>
	<d id="118">5.0E-6</d>
	<d id="119">5.0E-6</d>
	<d id="120">5.0E-6</d>
	<d id="121">5.0E-6</d>
	<d id="122">5.0E-6</d>
	<d id="123">6.0E-6</d>
	<d id="124">6.0E-6</d>
	<d id="125">6.0E-6</d>
	<d id="126">6.0E-6</d>
	<d id="127">6.0E-6</d>
	<d id="128">7.0E-6</d>
	<d id="129">7.0E-6</d>
	<d id="130">7.0E-6</d>
	<d id="131">7.0E-6</d>
	<d id="132">7.0E-6</d>
	<d id="133">8.0E-6</d>
	<d id="134">8.0E-6</d>
	<d id="135">8.0E-6</d>
	<d id="136">8.0E-6</d>
	<d id="137">9.0E-6</d>
	<d id="138">9.0E-6</d>
	<d id="139">9.0E-6</d>
	<d id="140">1.0E-5</d>
	<d id="141">1.0E-5</d>
	<d id="142">1.1E-5</d>
	<d id="143">1.1E-5</d>
	<d id="144">1.1E-5</d>
	<d id="145">1.2E-5</d>
	<d id="146">1.2E-5</d>
	<d id="147">1.3E-5</d>
	<d id="148">1.4E-5</d>
	<d id="149">1.4E-5</d>
	<d id="150">1.5E-5</d>
	<d id="151">1.5E-5</d>
	<d id="152">1.6E-5</d>
	<d id="153">1.6E-5</d>
	<d id="154">1.7E-5</d>
	<d id="155">1.8E-5</d>
	<d id="156">1.8E-5</d>
	<d id="157">1.9E-5</d>
	<d id="158">1.9E-5</d>
	<d id="159">2.0E-5</d>
	<d id="160">2.1E-5</d>
	<d id="161">2.1E-5</d>
	<d id="162">2.2E-5</d>
	<d id="163">2.3E-5</d>
	<d id="164">2.4E-5</d>
	<d id="165">2.4E-5</d>
	<d id="166">2.5E-5</d>
	<d id="167">2.6E-5</d>
	<d id="168">2.7E-5</d>
	<d id="169">2.8E-5</d>
	<d id="170">2.9E-5</d>
	<d id="171">3.0E-5</d>
	<d id="172">3.2E-5</d>
	<d id="173">3.3E-5</d>
	<d id="174">3.4E-5</d>
	<d id="175">3.6E-5</d>
	<d id="176">3.7E-5</d>
	<d id="177">3.8E-5</d>
	<d id="178">4.0E-5</d>
	<d id="179">4.1E-5</d>
	<d id="180">4.3E-5</d>
	<d id="181">4.4E-5</d>
	<d id="182">4.6E-5</d>
	<d id="183">4.7E-5</d>
	<d id="184">4.9E-5</d>
	<d id="185">5.0E-5</d>
	<d id="186">5.2E-5</d>
	<d id="187">5.3E-5</d>
	<d id="188">5.5E-5</d>
	<d id="189">5.8E-5</d>
	<d id="190">6.0E-5</d>
	<d id="191">6.3E-5</d>
	<d id="192">6.6E-5</d>
	<d id="193">6.9E-5</d>
	<d id="194">7.1E-5</d>
	<d id="195">7.4E-5</d>
	<d id="196">7.7E-5</d>
	<d id="197">8.1E-5</d>
	<d id="198">8.4E-5</d>
	<d id="199">8.7E-5</d>
	<d id="200">9.0E-5</d>
	<d id="201">9.4E-5</d>
	<d id="202">9.7E-5</d>
	<d id="203">1.01E-4</d>
	<d id="204">1.05E-4</d>
	<d id="205">1.08E-4</d>
	<d id="206">1.11E-4</d>
	<d id="207">1.13E-4</d>
	<d id="208">1.16E-4</d>
	<d id="209">1.18E-4</d>
	<d id="210">1.21E-4</d>
	<d id="211">1.28E-4</d>
	<d id="212">1.35E-4</d>
	<d id="213">1.42E-4</d>
	<d id="214">1.49E-4</d>
	<d id="215">1.56E-4</d>
	<d id="216">1.64E-4</d>
	<d id="217">1.71E-4</d>
	<d id="218">1.78E-4</d>
	<d id="219">1.86E-4</d>
	<d id="220">1.94E-4</d>
	<d id="221">2.02E-4</d>
	<d id="222">2.1E-4</d>
	<d id="223">2.18E-4</d>
	<d id="224">2.26E-4</d>
	<d id="225">2.34E-4</d>
	<d id="226">2.42E-4</d>
	<d id="227">2.5E-4</d>
	<d id="228">2.58E-4</d>
	<d id="229">2.66E-4</d>
	<d id="230">2.74E-4</d>
	<d id="231">2.82E-4</d>
	<d id="232">2.9E-4</d>
	<d id="233">2.99E-4</d>
	<d id="234">3.07E-4</d>
	<d id="235">3.15E-4</d>
	<d id="236">3.24E-4</d>
	<d id="237">3.32E-4</d>
	<d id="238">3.41E-4</d>
	<d id="239">3.5E-4</d>
	<d id="240">3.59E-4</d>
	<d id="241">3.77E-4</d>
	<d id="242">3.98E-4</d>
	<d id="243">4.19E-4</d>
	<d id="244">4.4E-4</d>
	<d id="245">4.61E-4</d>
	<d id="246">4.82E-4</d>
	<d id="247">5.04E-4</d>
	<d id="248">5.25E-4</d>
	<d id="249">5.46E-4</d>
	<d id="250">5.68E-4</d>
	<d id="251">5.87E-4</d>
	<d id="252">6.07E-4</d>
	<d id="253">6.26E-4</d>
	<d id="254">6.45E-4</d>
	<d id="255">6.64E-4</d>
	<d id="256">6.84E-4</d>
	<d id="257">7.03E-4</d>
	<d id="258">7.22E-4</d>
	<d id="259">7.41E-4</d>
	<d id="260">7.61E-4</d>
	<d id="261">7.82E-4</d>
	<d id="262">8.15E-4</d>
	<d id="263">8.48E-4</d>
	<d id="264">8.82E-4</d>
	<d id="265">9.17E-4</d>
	<d id="266">9.53E-4</d>
	<d id="267">9.9E-4</d>
	<d id="268">0.001028</d>
	<d id="269">0.001076</d>
	<d id="270">0.001126</d>
	<d id="271">0.001178</d>
	<d id="272">0.001231</d>
	<d id="273">0.001285</d>
	<d id="274">0.00134</d>
	<d id="275">0.001396</d>
	<d id="276">0.001453</d>
	<d id="277">0.001512</d>
	<d id="278">0.001571</d>
	<d id="279">0.001632</d>
	<d id="280">0.001693</d>
	<d id="281">0.001756</d>
	<d id="282">0.00182</d>
	<d id="283">0.001885</d>
	<d id="284">0.001951</d>
	<d id="285">0.002018</d>
	<d id="286">0.002086</d>
	<d id="287">0.002155</d>
	<d id="288">0.002226</d>
	<d id="289">0.002297</d>
	<d id="290">0.00237</d>
	<d id="291">0.002443</d>
	<d id="292">0.002515</d>
	<d id="293">0.002584</d>
	<d id="294">0.002653</d>
	<d id="295">0.002723</d>
	<d id="296">0.002794</d>
	<d id="297">0.002865</d>
	<d id="298">0.002996</d>
	<d id="299">0.003143</d>
	<d id="300">0.003295</d>
	<d id="301">0.00345</d>
	<d id="302">0.00361</d>
	<d id="303">0.003775</d>
	<d id="304">0.003943</d>
	<d id="305">0.004116</d>
	<d id="306">0.004294</d>
	<d id="307">0.004475</d>
	<d id="308">0.004654</d>
	<d id="309">0.004835</d>
	<d id="310">0.005018</d>
	<d id="311">0.005204</d>
	<d id="312">0.005393</d>
	<d id="313">0.005584</d>
	<d id="314">0.005778</d>
	<d id="315">0.005975</d>
	<d id="316">0.006175</d>
	<d id="317">0.006378</d>
	<d id="318">0.006583</d>
	<d id="319">0.006791</d>
	<d id="320">0.007001</d>
	<d id="321">0.007215</d>
	<d id="322">0.007431</d>
	<d id="323">0.00765</d>
	<d id="324">0.007872</d>
	<d id="325">0.008096</d>
	<d id="326">0.008319</d>
	<d id="327">0.008709</d>
	<d id="328">0.009139</d>
	<d id="329">0.009579</d>
	<d id="330">0.010031</d>
	<d id="331">0.010492</d>
	<d id="332">0.010965</d>
	<d id="333">0.011447</d>
	<d id="334">0.011941</d>
	<d id="335">0.012444</d>
	<d id="336">0.012958</d>
	<d id="337">0.013483</d>
	<d id="338">0.014014</d>
	<d id="339">0.014439</d>
	<d id="340">0.014865</d>
	<d id="341">0.015294</d>
	<d id="342">0.015727</d>
	<d id="343">0.016164</d>
	<d id="344">0.016605</d>
	<d id="345">0.017049</d>
	<d id="346">0.017496</d>
	<d id="347">0.017948</d>
	<d id="348">0.018403</d>
	<d id="349">0.018862</d>
	<d id="350">0.019324</d>
	<d id="351">0.019791</d>
	<d id="352">0.020261</d>
	<d id="353">0.020735</d>
	<d id="354">0.021747</d>
	<d id="355">0.023054</d>
	<d id="356">0.024383</d>
	<d id="357">0.025735</d>
	<d id="358">0.027108</d>
	<d id="359">0.028504</d>
	<d id="360">0.029923</d>
	<d id="361">0.031363</d>
	<d id="362">0.032826</d>
	<d id="363">0.034311</d>
	<d id="364">0.035818</d>
	<d id="365">0.037348</d>
	<d id="366">0.0389</d>
	<d id="367">0.040474</d>
	<d id="368">0.04207</d>
	<d id="369">0.043688</d>
	<d id="370">0.045329</d>
	<d id="371">0.046992</d>
	<d id="372">0.048677</d>
	<d id="373">0.050385</d>
	<d id="374">0.052114</d>
	<d id="375">0.053866</d>
	<d id="376">0.055641</d>
	<d id="377">0.057437</d>
	<d id="378">0.059256</d>
	<d id="379">0.061098</d>
	<d id="380">0.062943</d>
	<d id="381">0.064354</d>
	<d id="382">0.065684</d>
	<d id="383">0.067657</d>
	<d id="384">0.071577</d>
	<d id="385">0.075595</d>
	<d id="386">0.07968</d>
	<d id="387">0.083563</d>
	<d id="388">0.087089</d>
	<d id="389">0.090671</d>
	<d id="390">0.094302</d>
	<d id="391">0.097981</d>
	<d id="392">0.101703</d>
	<d id="393">0.105474</d>
	<d id="394">0.109293</d>
	<d id="395">0.113159</d>
	<d id="396">0.117069</d>
	<d id="397">0.12103</d>
	<d id="398">0.125035</d>
	<d id="399">0.129087</d>
	<d id="400">0.133191</d>
	<d id="401">0.137336</d>
	<d id="402">0.141534</d>
	<d id="403">0.145774</d>
