=== ilist2/linac-lego/LinacLego/test/dtdFiles/LinacLego.dtd
<!ELEMENT linacLego (header,linac)>
<!ATTLIST linacLego
    xmlns:xi   CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
	revNo       CDATA       #IMPLIED
	comment       CDATA       #IMPLIED
	title CDATA #REQUIRED>
<!ELEMENT header (xi:include|slotModels|cellModels|controlSettingMaps|controlSettingFiles)* >
<!ELEMENT xi:include (#PCDATA)>
<!ATTLIST xi:include
    href       CDATA       #IMPLIED
    parse      (xml|text)  "xml"
   xpointer   CDATA       #IMPLIED>
<!ELEMENT slotModels (slotModel*) >
<!ATTLIST slotModels
	xml:base CDATA #IMPLIED
	xmlns:xi CDATA #IMPLIED
	id CDATA #REQUIRED>
<!ELEMENT slotModel (var*,ble+)>
<!ATTLIST slotModel
	id CDATA #REQUIRED>
<!ELEMENT var (#PCDATA) >
<!ATTLIST var
	type CDATA #REQUIRED
	id CDATA #REQUIRED>
<!ELEMENT ble (d+) >
<!ATTLIST ble
	type CDATA #REQUIRED
	model CDATA #IMPLIED
	id CDATA #REQUIRED>
<!ELEMENT d (#PCDATA) >
<!ATTLIST d
	unit CDATA #IMPLIED
	type CDATA #IMPLIED
	id CDATA #REQUIRED>
<!ELEMENT tf (#PCDATA) >
<!ATTLIST tf
	power CDATA #REQUIRED>
<!ELEMENT setPoint (tf*) >
<!ATTLIST setPoint
	section CDATA #REQUIRED 
	cell CDATA #REQUIRED 
	slot CDATA #IMPLIED    
	ble CDATA #IMPLIED 
	dataId CDATA #REQUIRED>
<!ELEMENT cellModels (cellModel*) >
<!ATTLIST cellModels
	xml:base CDATA #IMPLIED
	xmlns:xi CDATA #IMPLIED
	id CDATA #REQUIRED>
<!ELEMENT cellModel (var*,slot+) >
<!ATTLIST cellModel
	id CDATA #REQUIRED>
<!ELEMENT slot (d|ble)* >
<!ATTLIST slot
	model CDATA #IMPLIED
	id CDATA #REQUIRED>
<!ELEMENT controlSettingMap (setPoint*) >
<!ATTLIST controlSettingMap
	unit CDATA #REQUIRED
	type CDATA #REQUIRED
	devName CDATA #REQUIRED>
<!ELEMENT controlSettingFile (#PCDATA) >
<!ELEMENT controlSettingMaps (controlSettingMap*) >
<!ATTLIST controlSettingMaps
	xmlns:xi CDATA #IMPLIED
	xml:base CDATA #IMPLIED
	id CDATA #REQUIRED>
<!ELEMENT controlSettingFiles (controlSettingFile*) >
<!ATTLIST controlSettingFiles
	xmlns:xi CDATA #IMPLIED
	xml:base CDATA #IMPLIED
	id CDATA #REQUIRED>
<!ELEMENT linac (linacData,(xi:include|section)*) >
<!ELEMENT linacData (d*) >
<!ELEMENT section (cell+) >
<!ATTLIST section
	xml:base CDATA #IMPLIED
	xmlns:xi CDATA #IMPLIED
	rfHarmonic CDATA #REQUIRED
	id CDATA #REQUIRED
	type CDATA #IMPLIED>
<!ELEMENT cell (slot|d)* >
<!ATTLIST cell
	id CDATA #REQUIRED
	model CDATA #IMPLIED>

=== ilist2/linac-lego/LinacLego/test/xmlFiles/spokeLego.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE linacLego SYSTEM "../dtdFiles/LinacLego.dtd">
<linacLego title="EssSpokeLinac" revNo="2" xmlns:xi="http://www.w3.org/2001/XInclude">
    <header>
        <slotModels id="SpokeSlotModels">
            <slotModel id="spokeLEDP">
                <var id="g1" type="double"/>
                <var id="g2" type="double"/>
                <ble id="DR0005" type="drift">
                    <d id="l" type="double" unit="mm">240</d>
                    <d id="r" type="double" unit="mm">20</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
                <ble id="DR0010" type="drift">
                    <d id="l" type="double" unit="mm">160</d>
                    <d id="r" type="double" unit="mm">30</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
                <ble id="QD0020" model="Quad310" type="quad">
                    <d id="l" type="double" unit="mm">310</d>
                    <d id="g" type="double" unit="T/m">g1</d>
                    <d id="r" type="double" unit="mm">30</d>
                </ble>
                <ble id="DR0030" type="drift">
                    <d id="l" type="double" unit="mm">460</d>
                    <d id="r" type="double" unit="mm">30</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
                <ble id="QD0040" model="Quad310" type="quad">
                    <d id="l" type="double" unit="mm">310</d>
                    <d id="g" type="double" unit="T/m">g2</d>
                    <d id="r" type="double" unit="mm">30</d>
                </ble>
                <ble id="DR0050" type="drift">
                    <d id="l" type="double" unit="mm">400</d>
                    <d id="r" type="double" unit="mm">30</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
            </slotModel>
            <slotModel id="spokeLwu">
                <var id="g1" type="double"/>
                <var id="g2" type="double"/>
                <ble id="DR0010" type="drift">
                    <d id="l" type="double" unit="mm">160</d>
                    <d id="r" type="double" unit="mm">30</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
                <ble id="QD0020" model="Quad310" type="quad">
                    <d id="l" type="double" unit="mm">310</d>
                    <d id="g" type="double" unit="T/m">g1</d>
                    <d id="r" type="double" unit="mm">30</d>
                </ble>
                <ble id="DR0030" type="drift">
                    <d id="l" type="double" unit="mm">460</d>
                    <d id="r" type="double" unit="mm">30</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
                <ble id="QD0040" model="Quad310" type="quad">
                    <d id="l" type="double" unit="mm">310</d>
                    <d id="g" type="double" unit="T/m">g2</d>
                    <d id="r" type="double" unit="mm">30</d>
                </ble>
                <ble id="DR0050" type="drift">
                    <d id="l" type="double" unit="mm">160</d>
                    <d id="r" type="double" unit="mm">30</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
            </slotModel>
            <slotModel id="spokeCryomodule">
                <var id="xelmax1" type="double"/>
                <var id="xelmax2" type="double"/>
                <var id="rfpdeg1" type="double"/>
                <var id="rfpdeg2" type="double"/>
                <ble id="DR0010" type="drift">
                    <d id="l" type="double" unit="mm">368.5</d>
                    <d id="r" type="double" unit="mm">28</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
                <ble id="FM0020" model="spokeCavity" type="fieldMap">
                    <d id="rfpdeg" type="double" unit="deg">rfpdeg1</d>
                    <d id="xelmax" type="double" unit="unit">xelmax1</d>
                    <d id="radiusmm" type="double" unit="mm">28</d>
                    <d id="lengthmm" type="double" unit="mm">994</d>
                    <d id="file" type="string" unit="unit">spokeFieldMap</d>
                    <d id="scaleFactor" type="double" unit="unit">1.0</d>
                </ble>
                <ble id="DR0030" type="drift">
                    <d id="l" type="double" unit="mm">135</d>
                    <d id="r" type="double" unit="mm">28</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
                <ble id="FM0040" model="spokeCavity" type="fieldMap">
                    <d id="rfpdeg" type="double" unit="deg">rfpdeg2</d>
                    <d id="xelmax" type="double" unit="unit">xelmax2</d>
                    <d id="radiusmm" type="double" unit="mm">28</d>
                    <d id="lengthmm" type="double" unit="mm">994</d>
                    <d id="file" type="string" unit="unit">spokeFieldMap</d>
                    <d id="scaleFactor" type="double" unit="unit">1.0</d>
                </ble>
                <ble id="DR0050" type="drift">
                    <d id="l" type="double" unit="mm">368.5</d>
                    <d id="r" type="double" unit="mm">28</d>
                    <d id="ry" type="double" unit="mm">0</d>
                </ble>
            </slotModel>
        </slotModels>
        <cellModels id="SpokeCellModels">
            <cellModel id="spokeLEDPCell">
                <var id="g1" type="double"/>
                <var id="g2" type="double"/>
                <var id="xelmax1" type="double"/>
                <var id="xelmax2" type="double"/>
                <var id="rfpdeg1" type="double"/>
                <var id="rfpdeg2" type="double"/>
                <slot id="slot010" model="spokeLEDP">
                    <d id="g1" type="double">g1</d>
                    <d id="g2" type="double">g2</d>
                </slot>
                <slot id="slot020" model="spokeCryomodule">
                    <d id="xelmax1" type="double">xelmax1</d>
                    <d id="xelmax2" type="double">xelmax2</d>
                    <d id="rfpdeg1" type="double">rfpdeg1</d>
                    <d id="rfpdeg2" type="double">rfpdeg2</d>
                </slot>
            </cellModel>
            <cellModel id="spokeCell">
                <var id="g1" type="double"/>
                <var id="g2" type="double"/>
                <var id="xelmax1" type="double"/>
                <var id="xelmax2" type="double"/>
                <var id="rfpdeg1" type="double"/>
                <var id="rfpdeg2" type="double"/>
                <slot id="slot010" model="spokeLwu">
                    <d id="g1" type="double">g1</d>
                    <d id="g2" type="double">g2</d>
                </slot>
                <slot id="slot020" model="spokeCryomodule">
                    <d id="xelmax1" type="double">xelmax1</d>
                    <d id="xelmax2" type="double">xelmax2</d>
                    <d id="rfpdeg1" type="double">rfpdeg1</d>
                    <d id="rfpdeg2" type="double">rfpdeg2</d>
                </slot>
            </cellModel>
        </cellModels>
		<setPoints id="SpokeSetPoints">
			<setPoint devName="SWU02-BMD:QH-010"> 
				<d id="setting" type="double" unit="Amps">4.85226</d>
				<cnpt section="SPOK" cell="cell020" slot="spokeLwu" ble="QD0020" id="g" >
					<tf id="0">0</tf>
					<tf id="1">1</tf>
				</cnpt>
			</setPoint>
			<setPoint devName="SWU02-BMD:QV-020"> 
				<d id="setting" type="double" unit="Amps">4.77927</d>
				<cnpt section="SPOK" cell="cell020" id="g2" >
					<tf id="0">0</tf>
					<tf id="1">-1</tf>
				</cnpt>
			</setPoint>
		</setPoints>
    </header>
    <linac>
        <linacData>
            <d id="ekin" type="double" unit="MeV">89.0</d>
            <d id="beamFrequency" type="double" unit="MHz">352.21</d>
            <d id="xSurvey" type="double" unit="m">0.0</d>
            <d id="ySurvey" type="double" unit="m">0.0</d>
            <d id="zSurvey" type="double" unit="m">0.0</d>
            <d id="pitchSurvey" type="double" unit="deg">0.0</d>
            <d id="rollSurvey" type="double" unit="deg">0.0</d>
            <d id="yawSurvey" type="double" unit="deg">0.0</d>
            <d id="alphaX" type="double" unit="unit">0.0</d>
            <d id="alphaY" type="double" unit="unit">0.0</d>
            <d id="alphaZ" type="double" unit="unit">0.0</d>
            <d id="betaX" type="double" unit="mm/mrad">0.0</d>
            <d id="betaY" type="double" unit="mm/mrad">0.0</d>
            <d id="betaZ" type="double" unit="deg/keV">0.0</d>
            <d id="emitX" type="double" unit="mm-mrad">0.0</d>
            <d id="emitY" type="double" unit="mm-mrad">0.0</d>
            <d id="emitZ" type="double" unit="deg-keV">0.0</d>
            <d id="beamCurrent" type="double" unit="mA">0.0</d>
        </linacData>
        <section id="SPOK" rfHarmonic="1">
            <cell id="cell010" model="spokeLEDPCell">
                <d id="g1" type="double">5.23025</d>
                <d id="g2" type="double">-4.68975</d>
                <d id="xelmax1" type="double">0.868945</d>
                <d id="xelmax2" type="double">0.865525</d>
                <d id="rfpdeg1" type="double">-6.65943</d>
                <d id="rfpdeg2" type="double">4.03247</d>
            </cell>
            <cell id="cell020" model="spokeCell">
                <d id="g1" type="double">4.85226</d>
                <d id="g2" type="double">-4.77927</d>
                <d id="xelmax1" type="double">0.890626</d>
                <d id="xelmax2" type="double">0.891124</d>
                <d id="rfpdeg1" type="double">22.0298</d>
                <d id="rfpdeg2" type="double">31.6618</d>
            </cell>
            <cell id="cell030" model="spokeCell">
